### ISSUE TITLE
Proposal: add autoupgrade 

### ISSUE THREAD

**Issue by doubleTroub1e** [sizifart/MuskEmpireBot#2]
hey, have you thought about implementing automatic purchase of upgrades? 
Project recently did an announcement that airdrop is going to take place at the end on September, so in scope of this info guess it would be worth doing that

**Comment by doubleTroub1e** [comment]
@sizifart  is it possible to implement?

**Comment by sizifart** [comment]
In the next update, all the checks and items will be added to the bot

**Comment by doubleTroub1e** [comment]
could be closed, found it already implemented here: https://github.com/Alexell/XEmpireBot
